name: transformation pipeline
on:
  push:
    branches:
      - main
jobs:
  pipeline:
    runs-on: ubuntu-latest 
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: run script
      run: ./run.sh
    - name: directory contents
      run: ls -al
